apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kiali

helmCharts:
  - name: kiali-operator
    repo: https://kiali.org/helm-charts
    version: 1.81.0
    releaseName: kiali-operator
    namespace: kiali
    includeCRDs: true
    valuesInline:
      cr:
        create: true
        namespace: istio-system
        spec:
          auth:
            strategy: anonymous
          istio_namespace: istio-system
          deployment:
            namespace: kiali
