apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

helmCharts:
  - name: kiali-server
    repo: https://kiali.org/helm-charts
    version: 1.19.0
    releaseName: kiali-server
    namespace: istio-system
    includeCRDs: true
    valuesInline:
      auth:
        strategy: anonymous
