apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

#resources:
#  - kiali.yaml
#  - prometheus.yaml

helmCharts:
  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.19.0
    releaseName: istio-base
    namespace: istio-system
    includeCRDs: true
  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.19.0
    releaseName: istiod
    namespace: istio-system
