apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.13.1
    releaseName: cert-manager
    namespace: cert-manager
    valuesInline:
      installCRDs: true