apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-rollouts/master/manifests/install.yaml

images:
  - name: quay.io/argoproj/argo-rollouts
    newTag: v1.6.0

configMapGenerator:
  - name: argo-rollouts-config
    behavior: merge
    files:
      - trafficRouterPlugins

patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: argo-rollouts
    path: patch-argo-rollouts-clusterrole.yaml
