apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-rollouts/master/manifests/install.yaml

images:
  - name: quay.io/argoproj/argo-rollouts
    newTag: v1.6.0
