apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: wait-for-rollout
spec:
  args:
    - name: rollout-name
    - name: rollout-namespace
    - name: rollout-weight-threshold
  metrics:
    - name: wait-for-rollout
      provider:
        job:
          spec:
            template:
              spec:
                serviceAccountName: kubectl-argo-rollouts
                containers:
                  - name: wait-for-rollout
                    image: 'ybelval/argo-rollouts-analysis:v1.3.1-26aef80'
                    args:
                      - --rollout-name
                      - "{{ args.rollout-name }}"
                      - --rollout-namespace
                      - "{{ args.rollout-namespace }}"
                      - --rollout-weight-threshold
                      - "{{ args.rollout-weight-threshold }}"
                restartPolicy: Never
