apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: canary-experiment
  labels:
    istio-injection: enabled
spec:
  templates:
    - name: canary
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/component: canary-experiment
          app.kubernetes.io/name: prototype
      template:
        metadata:
          labels:
            app.kubernetes.io/component: canary-experiment
            app.kubernetes.io/name: prototype
        spec:
          containers:
            - name: rollouts-demo-experiment
              image: argoproj/rollouts-demo:purple
              ports:
                - name: http
                  containerPort: 8080
                  protocol: TCP
