apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: canary-prototype
spec:
  hosts:
    - canary-prototype-stable.prototype.svc.cluster.local
  http:
    - name: stable
      route:
        - destination:
            host: canary-prototype-stable
          weight: 100
        - destination:
            host: canary-prototype-preview
          weight: 0
