apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- service.yaml
- rollout-1.yaml
- istio-virtual-service.yaml
- nginx-virtual-server.yaml
- analysis-template.yaml
- rbac.yaml

images:
  - name: argoproj/rollouts-demo
    newTag: purple