apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubectl-argo-rollouts-role
rules:
  - apiGroups:
      - ""
      - "apps"
      - "argoproj.io"
    resources:
      - '*'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
      - 'patch'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-argo-rollouts
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubectl-argo-rollouts-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubectl-argo-rollouts-role
subjects:
  - kind: ServiceAccount
    name: kubectl-argo-rollouts