apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary
spec:
  replicas: 3
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 60
  rollbackWindow: # https://argo-rollouts.readthedocs.io/en/stable/features/rollback/
    revisions: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: canary
      app.kubernetes.io/name: prototype
  template:
    metadata:
      labels:
        app: prototype
        version: yellow
        app.kubernetes.io/component: canary
        app.kubernetes.io/name: prototype
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:yellow
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
          timeoutSeconds: 30
  strategy:
    canary:
      canaryService: canary-prototype-preview
      stableService: canary-prototype-stable
      scaleDownDelaySeconds: 60
      scaleDownDelayRevisionLimit: 1
      trafficRouting:
        istio:
          virtualService:
            name: canary-prototype   # required
            routes:
              - stable            # optional if there is a single route in VirtualService, required otherwise
      steps:
      - setWeight: 20
      - setCanaryScale: # scale replicaset to 100% with only 20% traffic
          weight: 100
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}