apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#helmCharts:
#  - name: ingress-nginx
#    repo: https://kubernetes.github.io/ingress-nginx
#    version: 4.7.1
#    releaseName: ingress-nginx
#    namespace: ingress-nginx
#    valuesFile: values.yaml

resources:
  - ./nginx-ingress/common/ns-and-sa.yaml
  - ./nginx-ingress/rbac/rbac.yaml
  - ./nginx-ingress/common/nginx-config.yaml
  - ./nginx-ingress/common/ingress-class.yaml
  - ./nginx-ingress/common/crds/k8s.nginx.org_virtualservers.yaml
  - ./nginx-ingress/common/crds/k8s.nginx.org_virtualserverroutes.yaml
  - ./nginx-ingress/common/crds/k8s.nginx.org_transportservers.yaml
  - ./nginx-ingress/common/crds/k8s.nginx.org_policies.yaml
  - ./nginx-ingress/deployment/nginx-ingress.yaml
  - ./nginx-ingress/service/loadbalancer.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx-ingress
      spec:
        template:
          metadata:
            annotations:
              linkerd.io/inject: "enabled"
    target:
      kind: Deployment
      name: nginx-ingress
