apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

patches:
  - path: deployment.patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: metrics-server
      namespace: kube-system
