apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - sealed-secrets.yaml

helmCharts:
  - name: linkerd-crds
    repo: https://helm.linkerd.io/stable
    version: 1.8.0
    releaseName: linkerd-crds
    namespace: linkerd
    includeCRDs: true

