apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
  annotations:
    linkerd.io/inject: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
  labels:
    linkerd.io/is-control-plane: "true"
    config.linkerd.io/admission-webhooks: disabled
    linkerd.io/control-plane-ns: linkerd
---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-smi
  labels:
    linkerd.io/extension: smi
---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-viz
  labels:
    linkerd.io/extension: viz
