apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: locust
spec:
  ingressClassName: nginx
  rules:
  - host: locust.dev.argoproj.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: locust
            port:
              number: 8089